version: '3.5'
services:
    test:
        image: php:7.1.3
        volumes:
            - ./src:/home/src
            - ./specs:/home/specs
            - ./vendor:/home/vendor
        command: /home/vendor/bin/speckl
        working_dir: /home
